Add a better loader
Itay2805/virtdbg pull request #2
Opened 2021-03-26 18:55 UTC by Matt8898

2021-03-27 21:53 UTC, streaksu commented
This pull request contains code clearly copied from a BSD-2clause licensed project (for example, https://github.com/limine-bootloader/limine/blob/trunk/test/e9print.c is verbatim your e9 code), this means that for the proper use of the code, origin must be clearly stated, and the affected code must retain license, please specify that in the files, else the project could incur legal trouble.
Redirect to https://opensource.org/licenses/BSD-2-Clause for details.

2021-03-31 21:35 UTC, Itay2805 requested changes
Looks legit, I care less about the loader code quality just because it serves as a way to boot so I didn't look into it that in depth.

2021-03-31 21:35 UTC, Itay2805 commented on virtdbg/arch/intrin.c
> +    "mov %%cr3, %[value]"
This should be cr2, not cr3

2021-03-31 21:41 UTC, merged

2021-03-31 21:41 UTC, Itay2805 approved these changes